name: Deploy via SSH (Password Authentication)

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  deploy:
    environment: SIP_VM
    runs-on: ubuntu-latest

    steps:
      - name: Install Required Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y openconnect sshpass

      - name: Connect to VPN
        run: |
          sudo nohup openconnect gateway.iitk.ac.in --user=${{ secrets.VPN_USER }} --passwd-on-stdin --protocol=anyconnect <<< "${{ secrets.VPN_PASSWORD }}" &
          sleep 10  # Wait for VPN to establish

      - name: Connect via SSH and Deploy
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
          screen -S sip_frontend -X stuff '
            cd /home/vmadmin/SIP-Portal-Frontend && 
            git pull origin main
          '
          EOF
